name = "saffy"
main = "src/index.js"
compatibility_date = "2024-04-01"

[observability]
[observability.logs]
enabled = false
invocation_logs = true

#[mtls_certificates]
#binding = "CERT"
#certificate_id = "certificate_id"

[assets]
directory = "./dist"
binding = "ASSETS"