[server]
port = 3000
host = "127.0.0.1"
origin = "https://localhost:3000"
key_location = "key.pem" # needed to set up https
cert_location = "cert.pem"

[cas]
origin = "https://auth.bath.ac.uk"

[frontend]
dist = "/Users/bill/IdeaProjects/knowle/frontend/dist"