/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateIssue: {
      title?: string | null;
      description?: string | null;
      /** Format: uuid */
      locationUuid: string;
    };
    CreateReport: {
      /** Format: uuid */
      issueId: string;
      description: string;
    };
    Issue: {
      /** Format: uuid */
      id: string;
      title?: string | null;
      description?: string | null;
    };
    Report: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      issueId: string;
      /** Format: uuid */
      reporter: string;
      description?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      closedAt?: string | null;
    };
    User: {
      /** Format: uuid */
      id: string;
      username: string;
      /** Format: date-time */
      createdAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
